- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 15h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 15h
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 50
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BaseSkills
      # DS14-End

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackSecFilled # Corvax-Resprite-MRP
    outerClothing: ClothingOuterVestArmorSec
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  storage:
    back:
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - ERTloadoutSecuritySecondary # DS14

- type: chameleonOutfit
  id: SecurityCadetChameleonOutfit
  job: SecurityCadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesHudSecurity
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckScarfStripedRed
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
