- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 60
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BaseSkills
      # DS14-End

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    id: SecurityPDA # DS14
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - Flash
    - ERTloadoutSecuritySecondary # DS14

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
