- type: job
  id: CentralCommandOfficer
  name: job-name-centcom-officer
  description: job-description-centcom-officer
  playTimeTracker: JobCentralCommandOfficer
  setPreference: false
  startingGear: CentcomOfficerGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - ErtTeamLeader
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand

- type: startingGear
  id: CentcomOfficerGear
  equipment:
    # jumpsuit: ADTClothingUniformTurleneckGreenBlack
    # back: ClothingBackpackMilitarySatchel
    mask: ClothingMaskGasSecurity
    # shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatCentcomOfficer
    # eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretCentcomNaval
    id: CentcomPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetCentCom
    belt: ClothingBeltSecurityFilled

- type: chameleonOutfit
  id: CentralCommandOfficerChameleonOutfit
  job: CentralCommandOfficer
  equipment:
    mask: ClothingMaskGasSecurity
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterVestWeb
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretCentcomNaval
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltSecurityWebbingFilled
