# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  id: BaseAmmoRecipe
  categories:
  - Ammo
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseAmmoRecipe
  id: BaseEmptyAmmoRecipe
  completetime: 1

# DS14-Soyuz-start
- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipeLong
  id: BaseWeaponRecipeVeryLong
  completetime: 10
# DS14-Soyuz-end

# Recipes

- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Stunbaton
  result: Stunbaton

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Truncheon
  result: Truncheon

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShellTranquilizer
  result: BoxShellTranquilizer
  materials:
    Plastic: 240
    Steel: 160
    Glass: 80
    Plasma: 160
    Silver: 80

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  parent: TargetHuman
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: TargetHuman
  id: TargetSyndicate
  result: TargetSyndicate

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolEmpty
  result: MagazinePistolEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol
  result: MagazinePistol
  materials:
    Steel: 145

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolPractice
  result: MagazinePistolPractice
  materials:
    Steel: 85

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolUranium
  result: MagazinePistolUranium
  materials:
    Steel: 25
    Plastic: 65
    Uranium: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolIncendiary
  result: MagazinePistolIncendiary
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolSubMachineGunEmpty
  result: MagazinePistolSubMachineGunEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGun
  result: MagazinePistolSubMachineGun
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunUranium
  result: MagazinePistolSubMachineGunUranium
  materials:
    Steel: 25
    Plastic: 250
    Uranium: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunIncendiary
  result: MagazinePistolSubMachineGunIncendiary
  materials:
    Steel: 25
    Plastic: 275

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedEmpty
  result: MagazinePistolSubMachineGunTopMountedEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMounted
  result: MagazinePistolSubMachineGunTopMounted
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineRifleEmpty
  result: MagazineRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle
  result: MagazineRifle
  materials:
    Steel: 475


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRiflePractice
  result: MagazineRiflePractice
  materials:
    Steel: 175

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleUranium
  result: MagazineRifleUranium
  materials:
    Steel: 25
    Plastic: 300
    Uranium: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleIncendiary
  result: MagazineRifleIncendiary
  materials:
    Steel: 25
    Plastic: 450

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineLightRifleEmpty
  result: MagazineLightRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifle
  result: MagazineLightRifle
  materials:
    Steel: 565

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRiflePractice
  result: MagazineLightRiflePractice
  materials:
    Steel: 205


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleUranium
  result: MagazineLightRifleUranium
  materials:
    Steel: 25
    Plastic: 360
    Uranium: 360

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleIncendiary
  result: MagazineLightRifleIncendiary
  materials:
    Steel: 25
    Plastic: 540

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifle
  result: MagazineBoxRifle
  materials:
    Steel: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifle
  result: MagazineBoxLightRifle
  materials:
    Steel: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxLethalshot
  result: BoxLethalshot
  materials:
    Steel: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxBeanbag
  result: BoxBeanbag
  materials:
    Steel: 160
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunSlug
  result: BoxShotgunSlug
  materials:
    Steel: 240
    Plastic: 160

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: SpeedLoaderMagnumEmpty
  result: SpeedLoaderMagnumEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  materials:
    Steel: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumPractice
  result: SpeedLoaderMagnumPractice
  materials:
    Steel: 90

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumUranium
  result: SpeedLoaderMagnumUranium
  materials:
    Steel: 50
    Plastic: 150
    Uranium: 110

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumIncendiary
  result: SpeedLoaderMagnumIncendiary
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineShotgunEmpty
  result: MagazineShotgunEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgun
  result: MagazineShotgun
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunBeanbag
  result: MagazineShotgunBeanbag
  materials:
    Steel: 150
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunSlug
  result: MagazineShotgunSlug
  materials:
    Steel: 190
    Plastic: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunIncendiary
  result: MagazineShotgunIncendiary
  materials:
    Steel: 100
    Plastic: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolIncendiary
  result: MagazineBoxPistolIncendiary
  materials:
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumIncendiary
  result: MagazineBoxMagnumIncendiary
  materials:
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox357Incendiary
  result: MagazineBox357Incendiary
  materials:
    Plastic: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleIncendiary
  result: MagazineBoxLightRifleIncendiary
  materials:
    Plastic: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleIncendiary
  result: MagazineBoxRifleIncendiary
  materials:
    Plastic: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoader357
  result: SpeedLoader357
  materials:
    Steel: 1500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunFlare
  result: BoxShotgunFlare
  materials:
    Steel: 80
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunIncendiary
  result: BoxShotgunIncendiary
  materials:
    Steel: 80
    Plastic: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolPractice
  result: MagazineBoxPistolPractice
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumPractice
  result: MagazineBoxMagnumPractice
  materials:
    Steel: 60

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRiflePractice
  result: MagazineBoxLightRiflePractice
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRiflePractice
  result: MagazineBoxRiflePractice
  materials:
    Steel: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunPractice
  result: BoxShotgunPractice
  materials:
    Steel: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolUranium
  result: MagazineBoxPistolUranium
  materials:
    Plastic: 300
    Uranium: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumUranium
  result: MagazineBoxMagnumUranium
  materials:
    Plastic: 240
    Uranium: 180

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleUranium
  result: MagazineBoxLightRifleUranium
  materials:
    Plastic: 600
    Uranium: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleUranium
  result: MagazineBoxRifleUranium
  materials:
    Plastic: 500
    Uranium: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunUranium
  result: BoxShotgunUranium
  materials:
    Plastic: 320
    Uranium: 240

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  completetime: 6
  materials:
    Plastic: 100
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisabler
  result: WeaponDisabler
  completetime: 6
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: WeaponDisabler
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  id: MagazineGrenadeEmpty
  result: MagazineGrenadeEmpty
  completetime: 3
  materials:
    Steel: 150
    Plastic: 50

- type: latheRecipe
  id: GrenadeEMP
  result: GrenadeEMP
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: GrenadeBlast
  result: GrenadeBlast
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: GrenadeFlash
  result: GrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

# DS14-Soyuz-start
- type: latheRecipe
  parent: BaseGoldCircuitboardRecipe
  id: ArmedTechFabCircuitboard
  result: ArmedTechFabCircuitboard
  materials:
    Steel: 350
    Plastic: 150
    SheetTungsten: 100
    Silver: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolTungsten
  result: MagazinePistolTungsten
  materials:
    Steel: 25
    Plastic: 65
    SheetTungsten: 120
  
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTungsten
  result: MagazinePistolSubMachineGunTungsten
  materials:
    Steel: 25
    Plastic: 250
    SheetTungsten: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleTungsten
  result: MagazineRifleTungsten
  materials:
    Steel: 25
    Plastic: 300
    SheetTungsten: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleTungsten
  result: MagazineLightRifleTungsten
  materials:
    Steel: 25
    Plastic: 360
    SheetTungsten: 360

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumTungsten
  result: SpeedLoaderMagnumTungsten
  materials:
    Steel: 50
    Plastic: 150
    SheetTungsten: 110

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolTungsten
  result: MagazineBoxPistolTungsten
  materials:
    Plastic: 300
    SheetTungsten: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumTungsten
  result: MagazineBoxMagnumTungsten
  materials:
    Plastic: 240
    SheetTungsten: 180

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleTungsten
  result: MagazineBoxLightRifleTungsten
  materials:
    Plastic: 600
    SheetTungsten: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleTungsten
  result: MagazineBoxRifleTungsten
  materials:
    Plastic: 500
    SheetTungsten: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleAsVal
  result: MagazineLightRifleAsVal
  materials:
    Steel: 50
    Plastic: 300
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleAsValEmpty
  result: MagazineLightRifleAsValEmpty
  materials:
    Steel: 25
    Plastic: 50
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleAsValPractice
  result: MagazineLightRifleAsValPractice
  materials:
    Steel: 200
    Plastic: 50
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleAsValUranium
  result: MagazineLightRifleAsValUranium
  materials:
    Steel: 50
    Plastic: 300
    IngotTungsten: 100
    Uranium: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleAsValIncendiary
  result: MagazineLightRifleAsValIncendiary
  materials:
    Steel: 50
    Plastic: 400
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleAsValTungsten
  result: MagazineLightRifleAsValTungsten
  materials:
    Steel: 50
    Plastic: 300
    IngotTungsten: 100
    SheetTungsten: 360

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleVSS
  result: MagazineLightRifleVSS
  materials:
    Steel: 50
    Plastic: 150
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleVSSEmpty
  result: MagazineLightRifleVSSEmpty
  materials:
    Steel: 25
    Plastic: 25
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleVSSPractice
  result: MagazineLightRifleVSSPractice
  materials:
    Steel: 100
    Plastic: 50
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleVSSUranium
  result: MagazineLightRifleVSSUranium
  materials:
    Steel: 25
    Plastic: 150
    IngotTungsten: 100
    Uranium: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleVSSIncendiary
  result: MagazineLightRifleVSSIncendiary
  materials:
    Steel: 50
    Plastic: 200
    IngotTungsten: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleVSSTungsten
  result: MagazineLightRifleVSSTungsten
  materials:
    Steel: 50
    Plastic: 150
    IngotTungsten: 100
    SheetTungsten: 180

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponPistolMk58
  result: WeaponPistolMk58
  materials:
    Steel: 450
    Plastic: 350

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponRevolverPython
  result: WeaponRevolverPython
  materials:
    Steel: 450
    Wood: 150
    IngotTungsten: 150
    Silver: 150

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponShotgunKammerer
  result: WeaponShotgunKammerer
  materials:
    Steel: 750
    Wood: 450
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponShotgunEnforcer
  result: WeaponShotgunEnforcer
  materials:
    Steel: 900
    Plastic: 350
    Silver: 400

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponRifleAk
  result: WeaponRifleAk
  materials:
    Steel: 1350
    Plastic: 600
    IngotTungsten: 150
    Wood: 300

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponSubMachineGunDrozd
  result: WeaponSubMachineGunDrozd
  materials:
    Steel: 1000
    Plastic: 750
    Silver: 250
    Wood: 150

- type: latheRecipe
  parent: BaseWeaponRecipeVeryLong
  id: WeaponShotgunSaiga
  result: WeaponShotgunSaiga
  materials:
    Steel: 1400
    Plastic: 550
    Silver: 500
    SheetTungsten: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponRifleAKMCY
  result: WeaponRifleAKMCY
  materials:
    Steel: 1150
    Plastic: 450
    SheetTungsten: 350
    Wood: 300

- type: latheRecipe
  parent: BaseWeaponRecipeVeryLong
  id: WeaponRifleAsVal
  result: WeaponRifleAsVal
  materials:
    Steel: 1250
    Plastic: 450
    SheetTungsten: 350
    Silver: 350

- type: latheRecipe
  parent: BaseWeaponRecipeVeryLong
  id: WeaponRifleVSS
  result: WeaponRifleVSS
  materials:
    Steel: 1150
    Plastic: 550
    SheetTungsten: 300
    Silver: 300
    Wood: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleASH
  result: MagazineRifleASH
  materials:
    Steel: 350
    Plastic: 300
    IngotTungsten: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleASHEmpty
  result: MagazineRifleASHEmpty
  materials:
    Steel: 250
    Plastic: 150
    IngotTungsten: 200

- type: latheRecipe
  parent: BaseWeaponRecipeVeryLong
  id: WeaponRifleASH12
  result: WeaponRifleASH12
  materials:
    Steel: 2000
    Plastic: 1550
    Silver: 700
    SheetTungsten: 700
# DS14-Soyuz-end