- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # 1 hour
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: ClothingHandsGlovesBoxingRigged
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BaseSkills
      # DS14-End
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
    socks: ClothingUnderwearSocksBoxer
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BoxerChameleonOutfit
  job: Boxer
  equipment:
    head: ClothingHeadHatBlacksoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorGray
    jumpsuit: UniformShortsRedWithTop
    neck: ClothingNeckScarfStripedRed
