- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # 1 hour
  startingGear: ZookeeperGear
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MonkeyDay
    prototype: MonkeyCubeBox
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BaseSkills
      # DS14-End
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: ZookeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
    pocket1: HandheldHealthAnalyzer
    socks: ClothingUnderwearSocksZoo
  storage:
    back:
    - PetBowlWater

- type: chameleonOutfit
  id: ZookeeperChameleonOutfit
  job: Zookeeper
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorLightBrown
    neck: ClothingNeckScarfStripedBrown
    belt: ClothingBeltStorageWaistbag
    gloves: ClothingHandsGlovesColorBrown

