- type: department
  id: Taipan
  name: department-Taipan
  description: department-Taipan-description
  color: "#D381C9"
  roles:
  - TaipanAtmosTech
  - TaipanBotanist
  - TaipanCargotech
  - TaipanChef
  - TaipanMedic
  - TaipanRD
  - TaipanScience
  - TaipanTelecommunicationsOfficer

- type: department
  id: NKVB
  name: department-NKVB
  description: department-NKVB-description
  color: "#ad4040"
  roles:
  - Politkom
  - Politruk