- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 35
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BaseSkills
      # DS14-End

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    socks: ClothingUnderwearSocksNormal
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
