- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 20h
    - !type:OverallPlaytimeRequirement
      time: 40h
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-iaa
  canBeAntag: false
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: LawyerStampProvider
  - !type:AddComponentSpecial
    components:
    # DS14-Start
    - type: Skill
      group: BaseSkills
    # DS14-End
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 65
  #end-backmen: currency

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLaw
    socks: ClothingUnderwearSockLawyer
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - HyperLinkBookSOPLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
